language: d
d:
  - dmd
  - gdc
  - ldc
  - dmd-nightly
  - ldc-latest-ci
  - dmd-beta
  - ldc-beta

matrix:
  include:
    - os: windows
    - os: linux
      dist: bionic
    - os: osx

script:
  - cd tests && mkdir -p build && dub test -v

