language: d
d:
  - dmd
  - ldc
  - dmd-nightly
  - ldc-latest-ci
  - dmd-beta
  - ldc-beta

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CC=gcc-9;  fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-9; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

script:
  - cd tests && mkdir -p build
  - dub test --compiler=${DC} -v
